###user服务的端口号
server:
  port: 8003
###服务别名----服务注册到注册中心名称 
spring:
  application:
    ###服务名称(服务注册到zk上的名称)  
    name: zk-vip
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
## 开启断路器
feign:
  hystrix:
   enabled: true
#### hystrix禁止服务超时时间
hystrix:  
 command: 
   default: 
      execution: 
       timeout: 
        enabled: false