###user服务的端口号
server:
  port: 8002
###服务别名----服务注册到注册中心名称 
spring:
  application:
    ###服务名称(服务注册到zk上的名称)  
    name: zk-user
  ###数据源
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/books?useUnicode=true&characterEncoding=utf-8
    username: root
    password: feixiang
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181